// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:rick_and_morty/data/models/local/character_local.dart';
import 'package:rick_and_morty/data/models/local/episode_local.dart';
import 'package:rick_and_morty/data/models/local/location_local.dart';
import 'package:rick_and_morty/data/models/local/origin_local.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterLocalAdapter());
    registerAdapter(EpisodeLocalAdapter());
    registerAdapter(LocationLocalAdapter());
    registerAdapter(OriginLocalAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterLocalAdapter());
    registerAdapter(EpisodeLocalAdapter());
    registerAdapter(LocationLocalAdapter());
    registerAdapter(OriginLocalAdapter());
  }
}
