// Mocks generated by Mockito 5.4.6 from annotations
// in rick_and_morty/test/mocks/generated_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:rick_and_morty/core/paginated_response.dart' as _i8;
import 'package:rick_and_morty/core/result.dart' as _i4;
import 'package:rick_and_morty/data/repositories/character/character_repository.dart'
    as _i2;
import 'package:rick_and_morty/data/repositories/episode/episode_repository.dart'
    as _i7;
import 'package:rick_and_morty/domain/models/character.dart' as _i5;
import 'package:rick_and_morty/domain/models/episode.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CharacterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRepository extends _i1.Mock
    implements _i2.CharacterRepository {
  MockCharacterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Character>>> getCharactersByIds({
    required List<String>? ids,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCharactersByIds, [], {#ids: ids}),
            returnValue: _i3.Future<_i4.Result<List<_i5.Character>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Character>>>(
                this,
                Invocation.method(#getCharactersByIds, [], {#ids: ids}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Character>>>);
}

/// A class which mocks [EpisodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeRepository extends _i1.Mock implements _i7.EpisodeRepository {
  MockEpisodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i8.PaginatedResponse<_i9.Episode>>> getEpisodes({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisodes, [], {#page: page}),
            returnValue:
                _i3.Future<
                  _i4.Result<_i8.PaginatedResponse<_i9.Episode>>
                >.value(
                  _i6.dummyValue<
                    _i4.Result<_i8.PaginatedResponse<_i9.Episode>>
                  >(this, Invocation.method(#getEpisodes, [], {#page: page})),
                ),
          )
          as _i3.Future<_i4.Result<_i8.PaginatedResponse<_i9.Episode>>>);
}
